# This is a basic workflow to help you get started with Actions

name: Windows

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build command
    - name: Build
      shell: cmd
      run: '"%MSBUILD_PATH%\MSBuild.exe" Shtreeba.sln /p:Platform=x86 /p:Configuration=Release -m'
      
    # Prepare
    - name: Prepare
      shell: powershell
      run: 'mkdir Shtreeba; cp .\Release\Shtreeba.exe .\Shtreeba\; cp .\Release\Shtreeba.dll .\Shtreeba\'
       
    # Upload artifacts
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with: 
        name: Shtreeba-${{ github.sha }}
        path:  .\Shtreeba
